### ISSUE TITLE
License

### ISSUE THREAD

**Issue by YuqianSong6** [betheroot/sticky_elephant#9]
Hello @ffleming,

I'm currently working on an academic project and wanted to use the results obtained by running your honeypot as a part of a paper. I realized that you haven't put a license. I've already cited the repo in the paper but I'm not sure if that is enough. Could you please add a license or could you give me an answer on whether I could use your code?

Thank you

**Comment by ffleming** [comment]
What a silly oversight, sorry about that! The project uses the MIT license. I've added it to the codebase now, thanks for raising the issue! I'd love it if you could send a link to the paper, too, but of course there's no requirement to do so. I just think it'd be cool to read :) Cheers!

**Comment by YuqianSong6** [comment]
Thank you very much for the fast reply.
I'm still in the process of writing it. The deadline for the conference is in a few months so it could take a while. I'll update you on it if everything goes well.

**Comment by YuqianSong6** [comment]
Hello @ffleming the paper was accepted at Internet Measurement Conference 2025 and is out now, you can find it here for now: [link](https://gsmaragd.github.io/publications/IMC2025-DB/IMC2025-DB.pdf). It will be open access on the actual site after the conference starts I believe: https://conferences.sigcomm.org/imc/2025/accepted-papers/.
Thanks again for adding the license. Let me know if you have any questions.
